### ISSUE TITLE
does the sdk support offline map comed from the website: http://www.openandromaps.org/en/downloads/asia-middle-east? 

### ISSUE THREAD

**Issue by WiFiInHand** [nutiteq/hellomap3d-ios#12]
hi, 
  does the sdk support offline map comed from the website: http://www.openandromaps.org/en/downloads/asia-middle-east now?

these map is vector format? does the sdk support this format？

if support ， should I  use which datasource and layer to show?

if not support , which step I can do to add to implement it.

thanks in advance.

**Comment by mtehver** [comment]
This site site seems to use MapsForge packages, which are not supported in Nutiteq SDK3. Adding the support is very complicated (MapsForge itself is a Java library), so I do not suggest putting your effort into this. BTW, Nutiteq will soon have its own offline packages (for most countries, a single package will cover the country).

**Comment by WiFiInHand** [comment]
thanks your reply vrry much!

**Comment by eriklu** [comment]
is offline packages valid now? and where to download it?

**Comment by mtehver** [comment]
There is a sample in advancedmap folder (PackageManagerController) showing how to use PackageManager functionality. Details about PackageManager can be found here: https://developer.nutiteq.com/guides/offline-maps. 

We have also a full app in Android PlayStore built using Nutiteq offline service: Nutiteq Offline Maps (https://www.nutiteq.com/apps/offline-maps-3d/). The app has nice UI and some extra features compared to the sample.
