### ISSUE TITLE
Is pin clustering possible?

### ISSUE THREAD

**Issue by xrolfex** [nutiteq/hellomap3d-ios#13]
Im looking at potentially using this for a piece of software but have any where from a few hundred to 20K pins that would be shown, does this any any sort of clustering built in? I already saw it supported polygons which is another item I'm in need of.

**Comment by mtehver** [comment]
Sorry, marker clustering is not implemented in the samples nor in the SDK. But it could be implemented by creating a new data source class or by implementing it in the app logic.

**Comment by mtehver** [comment]
Pin clustering implemented in SDK 3.2RC1, advancedmap project contains samples using it.
