### ISSUE TITLE
Create Pod 

### ISSUE THREAD

**Issue by dimohamdy** [nutiteq/hellomap3d-ios#15]
please add butiteq to cocoa pod

**Comment by jaakla** [comment]
thanks. This is in our near TODO list, will have for 3.2.0 release

**Comment by jaakla** [comment]
There is one now: https://cocoapods.org/pods/Nutiteq . Note that you need to use RC version number until 3.2.0 release:
```
pod 'Nutiteq', '3.2.0-rc2'
```

**Comment by dimohamdy** [comment]
please update read.me
