### ISSUE TITLE
Nutiteq framework conflict with Spatialite library

### ISSUE THREAD

**Issue by hvbnet** [nutiteq/hellomap3d-ios#16]
I download sample from github (swift project)
then add SpatialDBKit via pod, and then try to open spatialite db, 
get exc_bad_access exception (code=1,address0x300) on spatialite init exactly when try to call sqlite3_auto_extension 

spatialite_init (int verbose)
{
/* used when SQLite initializes as an ordinary lib 
   OBSOLETE - strongly discuraged !!!!!
*/

#ifndef OMIT_GEOS       /* initializing GEOS */
    initGEOS (geos_warning, geos_error);
#endif /* end GEOS  */

    sqlite3_auto_extension ((void (*)(void)) init_spatialite_extension);
    spatialite_splash_screen (verbose);
}

**Comment by hvbnet** [comment]
this not your issue, sorry.
see https://github.com/andreacremaschi/SpatialDBKit/issues/21

**Comment by jaakla** [comment]
I checked this. Nutiteq works fine with spatialite Pod. This spatialite_init is some old method, if you call it then you get crash. But you do not need it, I tried with following code (and spatialite Pod):
```
#import <spatialite.h>
...

    sqlite3 *_db;
    NSString *sqLiteDb = [[NSBundle mainBundle] pathForResource:@"cities15000"
                                                         ofType:@"sqlite"];
    
    if (sqlite3_open([sqLiteDb UTF8String], &_db) != SQLITE_OK) {
        NSLog(@"Failed to open database!");
    }
    
    spatialite_init_geos();
    
    void *spatialite_conn;
    spatialite_conn = spatialite_alloc_connection();
    spatialite_init_ex(_db, spatialite_conn, 1);
    
    NSString* ver = [NSString stringWithFormat:@"spatialite version: %s", spatialite_version()];
    [NTLog debug: ver];
    
    NSString *query = @"SELECT name, asgeojson(transform(geometry,3857)) from cities15000";
...
// now you can load the objects, create Nutiteq geometries (e.g. Markers) from these using GeoJSON oarser and add these to NTLocalVectorDataSource, use also clustering etc

```
