### ISSUE TITLE
enable bitCode

### ISSUE THREAD

**Issue by dimohamdy** [nutiteq/hellomap3d-ios#17]
I have error when run in try to Archive  xcode 7 and on ios 9 
../Pods/Nutiteq/Nuti.framework/Nuti(libnutiteq_maps_sdk.a-armv7-master.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by jaakla** [comment]
Are you sure you use latest build (3.2.1 release version) ? This should have bitcode included. Even through it makes library much larger

**Comment by dimohamdy** [comment]
when is add 
pod 'Nutiteq'
I get this error 
/************/
[!] Due to the previous naïve CocoaPods resolver, you were using a pre-release version of `Nutiteq`, without explicitly asking for a pre-release version, which now leads to a conflict. Please decide to either use that pre-release version by adding the version requirement to your Podfile (e.g. `pod 'Nutiteq', '= 3.2.0-rc2'`) or revert to a stable version by running `pod update Nutiteq`.
/********
please update read.me

**Comment by dimohamdy** [comment]
please accept pull request
