### ISSUE TITLE
NTMapView screenToMap: function work incorrect

### ISSUE THREAD

**Issue by powerscin** [nutiteq/hellomap3d-ios#20]
I have UIPanGestureRecognizer and when gesture recognizer working I am try moving marker.

My code:

```
- (IBAction)moveMarker:(UIPanGestureRecognizer *)sender {
    CGPoint position = [sender locationInView:self.view];
    
    if(self.selectedMarker && sender.state == UIGestureRecognizerStateChanged) {
        NTMapPos* mapPos = [(NTMapView*)self.view screenToMap:[[NTScreenPos alloc] initWithX:position.x y:position.y]];
        [self.selectedMarker setPos:mapPos];
    }
}
```

And marker have incorrect position after this manipulation.

**Comment by jaakla** [comment]
Please repost it to one of dev channels: https://developer.nutiteq.com/support . This issue has nothing to do with the sample project here really.
