### ISSUE TITLE
KVO for map rotation

### ISSUE THREAD

**Issue by dimohamdy** [nutiteq/hellomap3d-ios#21]
can any one help me how the can make KVO for map rotation the only we to get rotation value getRotation method how i can observe change of get rotation

**Comment by jaakla** [comment]
you get mapMoved() event in MapListener. Please use following contacts for Nutiteq usage questions: https://www.nutiteq.com/nutiteq-sdk/support/ , if this is not a bug in sample app code

**Comment by dimohamdy** [comment]
mapMoved()  make called a lot of times ,thanks for fast replay but nutiteq  alot of thing
