### ISSUE TITLE
Cannot build project

### ISSUE THREAD

**Issue by igrrik** [nutiteq/hellomap3d-ios#22]
Hello, I'm trying to build sample project, but I can't do that.

At first it showed me the same problem as this guy's, though I've cloned the repo (not downloaded the zip).https://github.com/nutiteq/hellomap3d-ios/issues/19

After it, I've downloaded the SDK as you said, and replaced Nuti.framework and nutibright.zip

But now I get these errors:
![2016-02-05 12 12 17](https://cloud.githubusercontent.com/assets/4175212/12842160/ebee6fce-cc01-11e5-884f-f259ab8ed4d8.png)

**Comment by jaakla** [comment]
Right, you need latest development version of the SDK, not release, as release does not have Routing yet. You can get latest dev version from here: https://nutifront.s3.amazonaws.com/sdk_snapshots/sdk3-ios-build-102-c8c00e0cfece8633f05d101cf4884b2d756da0ea.zip
