### ISSUE TITLE
Balloon with custom content?

### ISSUE THREAD

**Issue by oooits72** [nutiteq/hellomap3d-ios#3]
Can I make ballon with custom content like UIView?
Shall I override
```objc
-(NTBitmap*)drawBitmap: (NTMapPos*)anchorScreenPos screenWidth: (float)screenWidth screenHeight: (float)screenHeight dpToPX: (float)dpToPX;
```
to solve my issue?
Can I see example code how to do this (C++ or ObjC or Swift)?

**Comment by mtehver** [comment]
Current version of hellomap3d-ios contains CustomPopup sample. If you need a custom design for your popup, you can use this sample as a base and customize it for your needs.
